# Generated by Django 6.1 on 2026-09-02 13:33

import comercial.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_customuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', comercial.models.CustomUserManager()),
            ],
        ),
    ]
